version: 2.0.2.{build}
configuration: Release
os: Visual Studio 2017
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
nuget:
  account_feed: true
before_build:
- ps: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: quiet
test:
  categories:
    except:
    - Integration
